version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: mysql8-dev
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"     
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  app:
      build:
        context: .
        dockerfile: Dockerfile.dev
      container_name: fullcycle-docker-nginx-app
      ports:
        - "3000:3000"
      environment:
        - PORT=3000
        - CHOKIDAR_USEPOLLING=true
        - DB_HOST=db
        - DB_PORT=3306
        - DB_USER=app
        - DB_PASSWORD=secret
        - DB_NAME=appdb
      volumes:
        - ./app:/usr/src/app
        - /usr/src/app/node_modules
      depends_on:
        db:
          condition: service_healthy
      restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  db_data:
